Update c-cpp-linter.yml

diff --git a/.github/workflows/c-cpp-linter.yml b/.github/workflows/c-cpp-linter.yml
--- a/.github/workflows/c-cpp-linter.yml
+++ b/.github/workflows/c-cpp-linter.yml
@@ -9,19 +9,44 @@ jobs:
   cpp-linter:
     runs-on: ubuntu-latest
     steps:
-
       - name: Check out the repo
         uses: actions/checkout@v4.1.0
+
+      - name: clang-format
+        uses: egor-tensin/clang-format@v1
         
       - uses: cpp-linter/cpp-linter-action@v2.6.1
         id: linter
+        continue-on-error: false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           style: file
+          tidy-checks: ''
           thread-comments: true
           step-summary: true
+          
+      # - name: clang-format-12 -style=Google path/to/filename.x
+      #   run: |
+      #     clang-format-12 -style=Google c-cpp-test/should-not-pass.c
+      #     clang-format-12 -style=Google c-cpp-test/test.c
+          
+  help-for-failed-ci:
+    if: steps.linter.outputs.checks-failed > 0
+    runs-on: ubuntu-latest
+    needs: cpp-linter
+    steps:
+      - name: Fail fast?!
+        run: |
+          echo "Some files failed the linting checks!"
+          echo "No. of checks failed: ${{ steps.linter.outputs.checks-failed }}"
+          echo "Use the clang-format diffs to find more help"
+
+      - name: Setup Python
+        uses: actions/setup-python@v4.7.1
 
       - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: echo "Some files failed the linting checks!"
+        uses: egor-tensin/clang-format@v1
+
+      - name: Trigger ci failed exit code 
+        run: exit 1
